ALTER TABLE "HomePageConfig"
ADD COLUMN "bannerFocalX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "bannerFocalY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "bannerFocalWidth" DOUBLE PRECISION NOT NULL DEFAULT 60,
ADD COLUMN "bannerFocalHeight" DOUBLE PRECISION NOT NULL DEFAULT 60;
