ALTER TABLE "SiteConfig"
  ADD COLUMN "saintsHeroFocalX" DOUBLE PRECISION NOT NULL DEFAULT 50,
  ADD COLUMN "saintsHeroFocalY" DOUBLE PRECISION NOT NULL DEFAULT 30,
  ADD COLUMN "traditionsHeroFocalX" DOUBLE PRECISION NOT NULL DEFAULT 50,
  ADD COLUMN "traditionsHeroFocalY" DOUBLE PRECISION NOT NULL DEFAULT 30,
  ADD COLUMN "mapHeroFocalX" DOUBLE PRECISION NOT NULL DEFAULT 50,
  ADD COLUMN "mapHeroFocalY" DOUBLE PRECISION NOT NULL DEFAULT 30;
