import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { researchBundleSchema } from "../lib/visit-place-domain";
const bundlePath=process.env.VISIT_RESEARCH_TEST_BUNDLE;
if(!bundlePath) throw Error("VISIT_RESEARCH_TEST_BUNDLE is required; research data is not committed to the repository.");
const bundle=researchBundleSchema.parse(JSON.parse(readFileSync(bundlePath,"utf8")));
const url=process.env.MUSEUM_TEST_DATABASE_URL;
if(!url||!["localhost","127.0.0.1"].includes(new URL(url).hostname)||new URL(url).pathname!=="/museum_integration_test") throw Error("Disposable local test database required");
process.env.DATABASE_URL=url;
const {db}=await import("../lib/db");
const {stageVisitPlaceResearch,decideVisitPlaceResearch}=await import("../lib/visit-place-review");
const {visitPlaceSchema}=await import("../lib/visit-place-domain");
try {
 const actor=await db.user.create({data:{email:"visit-review-fixture@example.invalid",roles:["data_admin"]}});
 const place=await db.place.create({data:{slug:"existing-location",name:"Existing reviewed place"}});
 for(const row of bundle.rows.slice(0,213)) await db.saint.create({data:{slug:String(row.slug),displayName:String(row.name),canonicalName:String(row.canonical_name),status:"published",places:{create:{placeId:place.id,placeType:"primary"}}}});
 const started=Date.now();
 assert.deepEqual(await stageVisitPlaceResearch(actor.id,bundle),{staged:214,unchanged:0,unmatched:1});
 assert.equal(await db.saint.count(),213);assert.equal(await db.place.count(),1);assert.equal(await db.saintPlace.count(),213);
 let row=await db.visitPlaceProposal.findFirstOrThrow({where:{saintId:{not:null}}});
 const original=JSON.stringify(row.rawJson);const normalized=visitPlaceSchema.parse(row.normalizedJson);
 const approve={id:row.id,version:1,action:"approve",catalogDecision:"review_needed",catalogNote:"Investigate old collection-site association",evidence:"Verified institutional source",confirm:"on"};
 await assert.rejects(decideVisitPlaceResearch(actor.id,approve,normalized));
 const edited={...normalized,coordinatePrecision:"locality"};
 row=await decideVisitPlaceResearch(actor.id,approve,edited);
 assert.equal(row.status,"approved");assert.equal(row.decisionNote,null);assert.equal(JSON.stringify(row.rawJson),original);
 assert.equal(await db.place.count(),1);assert.equal(await db.saintPlace.count(),213);
 await assert.rejects(decideVisitPlaceResearch(actor.id,approve,edited));
 assert.deepEqual(await stageVisitPlaceResearch(actor.id,bundle),{staged:0,unchanged:214,unmatched:0});
 row=await db.visitPlaceProposal.findUniqueOrThrow({where:{id:row.id}});assert.equal(row.status,"approved");assert.equal(row.catalogDecision,"review_needed");
 const unmatched=await db.visitPlaceProposal.findFirstOrThrow({where:{saintId:null}});
 await assert.rejects(decideVisitPlaceResearch(actor.id,{...approve,id:unmatched.id}, {...visitPlaceSchema.parse(unmatched.normalizedJson),coordinatePrecision:"locality"}));
 const deferred=await db.visitPlaceProposal.findFirstOrThrow({where:{status:"pending",saintId:{not:null}}});
 await decideVisitPlaceResearch(actor.id,{id:deferred.id,version:1,action:"defer",catalogDecision:"unreviewed",note:"Needs independent source"},deferred.normalizedJson);
 const slug=visitPlaceSchema.parse(deferred.normalizedJson).slug;
 const changed={...bundle,rows:bundle.rows.map(r=>r.slug===slug?{...r,research_notes:"Updated research evidence"}:r)};
 assert.deepEqual(await stageVisitPlaceResearch(actor.id,changed),{staged:1,unchanged:213,unmatched:0});
 assert.equal((await db.visitPlaceProposal.findUniqueOrThrow({where:{id:deferred.id}})).status,"superseded");
 await assert.rejects(decideVisitPlaceResearch(actor.id,{id:deferred.id,version:2,action:"approve",catalogDecision:"keep",evidence:"Source",confirm:"on"},{...visitPlaceSchema.parse(deferred.normalizedJson),coordinatePrecision:"locality"}));
 const duplicate={...bundle,rows:[bundle.rows[0],bundle.rows[0]]};await assert.rejects(stageVisitPlaceResearch(actor.id,duplicate));
 assert.equal(await db.visitPlaceProposal.count(),215);assert.equal(await db.saint.count(),213);assert.equal(await db.saintPlace.count(),213);
 assert.ok(await db.auditEvent.count({where:{entityType:"VisitPlaceProposal"}})>=217);
 console.log(`PASS 214-row staging/replay, raw preservation, approval prerequisites, separate catalog decision, stale edit/source protection, unmatched identity blocking, no canonical/public changes (${Date.now()-started}ms)`);
} finally {await db.$disconnect();}
