import assert from "node:assert/strict";
const url=process.env.MUSEUM_MEMBERSHIP_TEST_DATABASE_URL;
if(!url)throw Error("Set the disposable local museum_membership_test database URL");
const target=new URL(url);
if(!["localhost","127.0.0.1"].includes(target.hostname)||target.pathname!=="/museum_membership_test")throw Error("Refusing to test outside the disposable local membership database");
process.env.DATABASE_URL=url;
const {db}=await import("../lib/db");
const {readMuseumData}=await import("../lib/museum-working-data");
const {changeMuseumDisplayMembership,requestMuseumRelationshipCorrection}=await import("../lib/museum-display-membership");
const {moveMuseumFamilyProposal}=await import("../lib/museum-family-moves");
const {getMuseumProposalData}=await import("../lib/museum-proposals");
const suffix=String(Date.now());
try {
 const actor=await db.user.create({data:{email:`membership-${suffix}@example.invalid`,active:true,roles:["curator"]}});
 const original=getMuseumProposalData();
 const source=original.placements.find(p=>p.familyId && original.placements.filter(q=>q.familyId===p.familyId && !q.curatorialFamily).length>1 && !p.curatorialFamily)!;
 const before=(await readMuseumData()).placements.find(p=>p.id===source.id)!;
 const group=before.displayMembership!;
 await changeMuseumDisplayMembership({placementId:before.id,familyKey:group.familyKey,revision:group.revision,action:"detach",actorId:actor.id});
 const detached=(await readMuseumData()).placements.find(p=>p.id===source.id)!;
 assert.equal(detached.familyId,"");assert.equal(detached.section,before.section);
 await assert.rejects(changeMuseumDisplayMembership({placementId:before.id,familyKey:group.familyKey,revision:group.revision,action:"detach",actorId:actor.id}),/changed/);
 let data=await readMuseumData();const option=data.familyMoveOptions.find(f=>f.key===group.familyKey)!;
 const destination=data.sections.find(s=>s.name!==before.section)!.name;
 await moveMuseumFamilyProposal({familyKey:option.key,revision:option.revision,section:destination,actorId:actor.id});
 const afterMove=(await readMuseumData()).placements.find(p=>p.id===source.id)!;
 assert.equal(afterMove.section,before.section);assert.equal(afterMove.displayMembership?.detached,true);
 await assert.rejects(changeMuseumDisplayMembership({placementId:afterMove.id,familyKey:group.familyKey,revision:detached.displayMembership!.revision,action:"restore",actorId:actor.id}),/changed/);
 await changeMuseumDisplayMembership({placementId:afterMove.id,familyKey:group.familyKey,revision:afterMove.displayMembership!.revision,action:"restore",actorId:actor.id});
 assert.equal((await readMuseumData()).placements.find(p=>p.id===source.id)!.section,destination);
 console.log("PASS source detach, stale form rejection, exclusion from family moves and restore");
 const saint=await db.saint.create({data:{slug:"membership-"+suffix,displayName:"Membership fixture",canonicalName:"Membership fixture"}});
 const other=await db.saint.create({data:{slug:"membership-other-"+suffix,displayName:"Relationship fixture",canonicalName:"Relationship fixture"}});
 const relationship=await db.saintRelationship.create({data:{fromSaintId:saint.id,toSaintId:other.id,relationshipType:"guru",status:"published"}});
 const section=await db.museumSection.create({data:{slug:"membership-section-"+suffix,name:"Membership section "+suffix,status:"published"}});
 const exhibit=await db.museumExhibitGroup.create({data:{museumSectionId:section.id,key:"test",label:"Test display",anchorSaintId:saint.id}});
 const assignment=await db.saintMuseumSection.create({data:{saintId:saint.id,museumSectionId:section.id,assignmentType:"primary",tier:"featured",status:"published",exhibitGroupId:exhibit.id}});
 const museum=await db.museum.upsert({where:{id:"museum-spn"},create:{id:"museum-spn",slug:"spn",name:"SPN"},update:{}});
 const location=await db.museumLocation.create({data:{museumId:museum.id,code:"test-"+suffix,label:"Unchanged location",kind:"shelf"}});
 const item=await db.museumCollectionItem.create({data:{catalogMuseumId:museum.id,label:"Test relic",status:"verified"}});
 await db.museumItemSaint.create({data:{itemId:item.id,saintId:saint.id}});
 const placement=await db.museumItemPlacement.create({data:{itemId:item.id,locationId:location.id}});
 const read=async()=>(await readMuseumData()).placements.find(p=>p.id===assignment.id)!;
 const current=await read();
 await changeMuseumDisplayMembership({placementId:current.id,familyKey:current.displayMembership!.familyKey,revision:current.displayMembership!.revision,action:"detach",actorId:actor.id});
 const removed=await read();assert.equal(removed.familyId,"");assert.equal(removed.section,section.name);
 assert.equal((await db.museumExhibitGroup.findUniqueOrThrow({where:{id:exhibit.id}})).anchorSaintId,null);
 assert.equal((await db.museumItemPlacement.findUniqueOrThrow({where:{id:placement.id}})).endedAt,null);
 assert.equal(await db.museumItemSaint.count({where:{itemId:item.id,saintId:saint.id}}),1);
 assert.equal((await db.saintRelationship.findUniqueOrThrow({where:{id:relationship.id}})).status,"published");
 await changeMuseumDisplayMembership({placementId:removed.id,familyKey:removed.displayMembership!.familyKey,revision:removed.displayMembership!.revision,action:"restore",actorId:actor.id});
 assert.equal((await db.museumExhibitGroup.findUniqueOrThrow({where:{id:exhibit.id}})).anchorSaintId,saint.id);
 assert.equal((await read()).familyId,"exhibit:"+exhibit.id);
 await requestMuseumRelationshipCorrection({saintId:saint.id,note:"The guru relationship requires source verification.",actorId:actor.id});
 await requestMuseumRelationshipCorrection({saintId:saint.id,note:"The guru relationship requires source verification.",actorId:actor.id});
 assert.equal(await db.reconciliationIssue.count({where:{entityId:saint.id,issueType:"museum_relationship_correction",status:"open"}}),1);
 assert.equal((await db.saintRelationship.findUniqueOrThrow({where:{id:relationship.id}})).status,"published");
 console.log("PASS canonical detach/restore, anchor restoration, physical and historical preservation, separate correction request");
} finally {await db.$disconnect();}
