import assert from "node:assert/strict";
const url=process.env.MUSEUM_TEST_DATABASE_URL;
if(!url||!["localhost","127.0.0.1"].includes(new URL(url).hostname)||new URL(url).pathname!=="/museum_integration_test") throw Error("Disposable local museum_integration_test required");
process.env.DATABASE_URL=url;
const {db}=await import("../lib/db");const {planItemMove,resolveItemMove}=await import("../lib/museum-item-moves");
const {stageMirroredRelics}=await import("../lib/museum-relic-review");
try {
 const actor=await db.user.create({data:{email:"move-fixture@example.invalid",roles:["curator"]}});
 const saint=await db.saint.create({data:{displayName:"Move test saint",canonicalName:"Move test saint",slug:"move-test"}});
 const base="appMapiXrtNwnS9oZ";
 await db.airtableMirrorRecord.create({data:{baseId:base,tableIdOrName:"Saints",recordId:"recSaint",rawFieldsJson:{Name:"Move test saint","Vitrine #":12,Shelf:"A"},rawPayloadJson:{}}});
 await db.airtableMirrorRecord.create({data:{baseId:base,tableIdOrName:"Relics",recordId:"recRelic",rawFieldsJson:{"Item Name":"Relic",Saint:["recSaint"]},rawPayloadJson:{}}});
 await db.externalRecord.create({data:{sourceType:"airtable",entityType:"Saint",entityId:saint.id,externalId:base+":Saints:recSaint",rawPayloadJson:{}}});
 await stageMirroredRelics(actor.id);
 const item=await db.museumCollectionItem.findFirstOrThrow();
 const current=()=>db.museumItemPlacement.findFirstOrThrow({where:{itemId:item.id,endedAt:null},include:{location:true}});
 const propose=(v:string,version=0)=>planItemMove(actor.id,{itemId:item.id,version,vitrine:v,shelf:"A",reason:"Curatorial plan"});
 await assert.rejects(propose("12"));
 let plan=await propose("13");assert.equal((await current()).location.code,"12/A");
 assert.equal(await db.museumItemPlacement.count(),1);
 await assert.rejects(propose("14"));
 await assert.rejects(resolveItemMove(actor.id,{itemId:item.id,planId:plan.id,action:"complete",note:"No physical confirmation"}));
 await resolveItemMove(actor.id,{itemId:item.id,planId:plan.id,action:"cancel",note:"Keep current arrangement"});
 assert.equal((await current()).location.code,"12/A");
 plan=await propose("13");
 const complete={itemId:item.id,planId:plan.id,action:"complete" as const,note:"Physical move verified",confirm:"on" as const};
 await resolveItemMove(actor.id,complete);
 assert.equal((await current()).location.code,"13/A");assert.equal(await db.museumItemPlacement.count(),2);
 await assert.rejects(resolveItemMove(actor.id,complete));
 assert.equal((await db.museumCollectionItem.findUniqueOrThrow({where:{id:item.id}})).version,1);
 await stageMirroredRelics(actor.id);assert.equal((await current()).location.code,"13/A");
 plan=await propose("14",1);
 await db.museumCollectionItem.update({where:{id:item.id},data:{version:{increment:1}}});
 await assert.rejects(resolveItemMove(actor.id,{...complete,planId:plan.id}));
 await resolveItemMove(actor.id,{itemId:item.id,planId:plan.id,action:"cancel",note:"Source review changed item; replan"});
 plan=await propose("15",2);await db.museumLocation.update({where:{id:plan.targetLocationId},data:{archivedAt:new Date()}});
 await assert.rejects(resolveItemMove(actor.id,{...complete,planId:plan.id}));
 await resolveItemMove(actor.id,{itemId:item.id,planId:plan.id,action:"cancel",note:"Destination unavailable"});
 const foreign=await db.museumCollectionItem.create({data:{label:"Other museum item",catalogMuseumId:"museum-vrindavan"}});
 await assert.rejects(planItemMove(actor.id,{itemId:foreign.id,version:0,vitrine:"12",shelf:"",reason:"Wrong museum"}));
 assert.equal(await db.saint.count(),1);
 assert.equal((await current()).location.code,"13/A");
 console.log("PASS plan leaves current placement intact, cancel, physical confirmation, replay/duplicate protection, version conflict, archived destination, museum scope, location history and source replay preserving curator move");
} finally {await db.$disconnect();}
