import assert from "node:assert/strict";
const url=process.env.MUSEUM_TEST_DATABASE_URL;
if(!url||!["localhost","127.0.0.1"].includes(new URL(url).hostname)||new URL(url).pathname!=="/museum_integration_test")throw Error("Disposable local test database required");
process.env.DATABASE_URL=url;
const {db}=await import("../lib/db");
const {decideMuseumSource}=await import("../lib/museum-source-review-service");
const {startMuseumUpdate,runMuseumUpdate}=await import("../lib/museum-update-service");
const {SPN_WEBSITE_AIRTABLE_BASE_ID:base}=await import("../lib/museum-vitrine-source");
process.env.AIRTABLE_BASE_ID=base;process.env.AIRTABLE_ACCESS_TOKEN="test-only";delete process.env.AIRTABLE_VIEW;
const original=globalThis.fetch;
let saints=[{id:"recA",fields:{Name:"Source name","Vitrine #":12,Shelf:"C"}},{id:"recB",fields:{Name:"New source","Vitrine #":13}}];
let failRelics=false;
let relics=[{id:"recRelic",fields:{"Item Name":"Test item",Saint:["recA"]}}];
globalThis.fetch=async input=>{const url=new URL(String(input));const table=url.pathname.split("/").pop();const records=table==="Saints"?saints:relics;const offset=Number(url.searchParams.get("offset")||0);return new Response(JSON.stringify({records:records.slice(offset,offset+100),...(offset+100<records.length?{offset:String(offset+100)}:{})}),{status:table==="Relics"&&failRelics?503:200,headers:{"Content-Type":"application/json"}});};
try {
 const saint=await db.saint.create({data:{slug:"update-fixture",displayName:"Reviewed website name",canonicalName:"Reviewed website name"}});
 await db.externalRecord.create({data:{sourceType:"airtable",externalId:`${base}:Saints:recA`,entityType:"Saint",entityId:saint.id,rawPayloadJson:{}}});
 const one=await startMuseumUpdate("test-actor"),two=await startMuseumUpdate("test-actor");assert.equal(one.job.id,two.job.id);assert.equal(two.started,false);
 await runMuseumUpdate(one.job.id);assert.equal((await db.museumUpdateJob.findUniqueOrThrow({where:{id:one.job.id}})).status,"completed");
 assert.equal(await db.airtableMirrorRecord.count(),3);assert.equal((await db.saint.findUniqueOrThrow({where:{id:saint.id}})).displayName,"Reviewed website name");
 assert.equal((await db.externalRecord.findUniqueOrThrow({where:{sourceType_externalId:{sourceType:"airtable",externalId:`${base}:Saints:recA`}}})).entityId,saint.id);
 assert.equal(await db.saint.count(),1);assert.equal(await db.museumSourceReview.count(),1);assert.equal(await db.museumCollectionItem.count(),0);
 await runMuseumUpdate(one.job.id);assert.equal(await db.importBatch.count(),1);
 const review=await db.museumSourceReview.findFirstOrThrow();await db.museumSourceReview.update({where:{id:review.id},data:{status:"deferred",note:"Ask curator"}});
 const repeat=await startMuseumUpdate("test-actor");await runMuseumUpdate(repeat.job.id);assert.equal((await db.museumSourceReview.findUniqueOrThrow({where:{id:review.id}})).status,"deferred");
 saints[1].fields["Vitrine #"]=14;const change=await startMuseumUpdate("test-actor");await runMuseumUpdate(change.job.id);assert.equal((await db.museumSourceReview.findUniqueOrThrow({where:{id:review.id}})).status,"pending");assert.equal(await db.museumSourceReview.count(),1);
 const freshReview=await db.museumSourceReview.findUniqueOrThrow({where:{id:review.id}});
 await assert.rejects(decideMuseumSource("test-actor",{id:review.id,version:new Date(0).toISOString(),action:"link",saintId:saint.id,note:"stale form"}));
 await decideMuseumSource("test-actor",{id:review.id,version:freshReview.updatedAt.toISOString(),action:"link",saintId:saint.id,note:"Confirmed identity"});
 assert.equal((await db.externalRecord.findUniqueOrThrow({where:{sourceType_externalId:{sourceType:"airtable",externalId:`${base}:Saints:recB`}}})).entityId,saint.id);
 const linkedReview=await db.museumSourceReview.findUniqueOrThrow({where:{id:review.id}});
 await assert.rejects(decideMuseumSource("test-actor",{id:review.id,version:linkedReview.updatedAt.toISOString(),action:"link",saintId:saint.id,note:"Do not reassign"}));
 assert.ok((await db.museumUpdateJob.findUniqueOrThrow({where:{id:one.job.id}})).sourceSnapshot);
 const count=await db.importBatch.count();failRelics=true;saints[0].fields["Vitrine #"]=99;const failed=await startMuseumUpdate("test-actor");await runMuseumUpdate(failed.job.id);assert.equal((await db.museumUpdateJob.findUniqueOrThrow({where:{id:failed.job.id}})).status,"failed");assert.equal(await db.importBatch.count(),count);
 const raw=await db.airtableMirrorRecord.findFirstOrThrow({where:{recordId:"recA"}});assert.equal((raw.rawFieldsJson as any)["Vitrine #"],12);
 failRelics=false;saints=saints.slice(0,1);const missing=await startMuseumUpdate("test-actor");await runMuseumUpdate(missing.job.id);assert.equal((await db.museumUpdateJob.findUniqueOrThrow({where:{id:missing.job.id}})).status,"failed");assert.equal(await db.airtableMirrorRecord.count(),3);
 const interrupted=await startMuseumUpdate("test-actor");await db.museumUpdateJob.update({where:{id:interrupted.job.id},data:{leaseUntil:new Date(0)}});const retry=await startMuseumUpdate("test-actor");assert.notEqual(retry.job.id,interrupted.job.id);assert.equal((await db.museumUpdateJob.findUniqueOrThrow({where:{id:interrupted.job.id}})).status,"interrupted");
 saints=[{id:"recA",fields:{Name:"Source name","Vitrine #":12,Shelf:"C"}},{id:"recB",fields:{Name:"New source","Vitrine #":14}},...Array.from({length:1421},(_,i)=>({id:`recScale${i}`,fields:{Name:`Scale source ${i}`,"Vitrine #":12}}))];
 relics=[...relics,...Array.from({length:1310},(_,i)=>({id:`recItem${i}`,fields:{"Item Name":`Scale item ${i}`,Saint:["recA"]}}))];
 const scaleStart=Date.now();await runMuseumUpdate(retry.job.id);const scaleJob=await db.museumUpdateJob.findUniqueOrThrow({where:{id:retry.job.id}});assert.equal(scaleJob.status,"completed",scaleJob.progress);
 assert.equal(await db.airtableMirrorRecord.count(),2734);assert.equal(await db.saint.count(),1);
 console.log(`PASS paginated 1423 Saints / 1311 Relics refresh in ${Math.round((Date.now()-scaleStart)/1000)} seconds on disposable database.`);
 console.log("PASS museum updates: atomic failures, repeated jobs, preserved content/links, review deduplication and reopening, interrupted-job recovery.");
} finally {globalThis.fetch=original;await db.$disconnect();}
